### ISSUE TITLE
EP02 - Pitch Service 

### ISSUE THREAD

**Issue by iagocabral** [eps20241-pitchit/pitchit-docs#5]
## Descrição
Épico reune todas as funcionalidades relacionadas a geração do Pitch.

## User Stories:
- F01: Geração automática de pitches
- [ ] US04: Eu, como um empreendedor/startup, desejo gerar um pitch com base nas informações da minha empresa, para que eu possa aumentar as chances de obter investimentos ou parcerias.
- [ ] US05: Eu, como um estudante de EPS, desejo gerar um pitch com base nas informações do meu projeto, para que eu possa apresentar de forma eficiente e profissional.
- [ ] US06: Eu, como um usuário, desejo acessar templates de pitches para diferentes setores e objetivos, para que eu possa escolher o modelo mais adequado para a minha apresentação.

- F02: Fornecer orientações sobre apresentação
- [ ] US07: Eu, como um usuário, desejo acessar orientações sobre como estruturar minha apresentação, para garantir que meu pitch seja claro e eficaz.
- [ ] US08: Eu, como um usuário, desejo obter dicas sobre como projetar visualmente minha apresentação, para torná-la mais impactante.
- [ ] US09: Eu, como um usuário, desejo acessar orientações sobre habilidades de comunicação e oratória, para melhorar minha apresentação e aumentar minha confiança.
  
- F03: Melhorias no pitch
- [ ] US10: Eu, como um usuário, desejo saber quais são os principais tópicos do meu pitch, para garantir que abordei todos os pontos importantes.
- [ ] US11: Eu, como um usuário, desejo sugerir melhorias no pitch gerado, para ajustá-lo às necessidades e expectativas do público-alvo.
 
- F07: Salvar pitch
- [ ] US12: Eu, como um usuário, desejo salvar meu pitch, para que possa revisá-lo posteriormente.
- [ ] US13: Eu, como um usuário, desejo salvar meu pitch automaticamente, para que não perca o progresso caso ocorra um problema inesperado.
- [ ] US14: Eu, como um usuário, desejo organizar meus pitches salvos por categorias/etiquetas, para que possa encontrar rapidamente os pitches relevantes quando necessário.
- [ ] US15: Eu, como um usuário, desejo armazenar versões diferentes do meu pitch, para que possa acessar e comparar as versões conforme necessário.
  
- F15: Editar da pitch
- [ ] US16: Eu, como um usuário, desejo personalizar o pitch gerado com base no perfil do público-alvo, para que eu possa adaptar minha apresentação às necessidades do meu público.
- [ ] US17: Eu, como um usuário, desejo editar o pitch gerado para adicionar ou remover conteúdo, para que eu possa personalizar a apresentação de acordo com as preferências e dados disponíveis.
