### ISSUE TITLE
EP01 - Controle de Acesso

### ISSUE THREAD

**Issue by iagocabral** [eps20241-pitchit/pitchit-docs#6]
## Descrição
Integração com service de controle de acesso de outro grupo de EPS.

## User Stories:
- [ ]  Eu, como um usuário, desejo criar uma conta, para que possa acessar as funcionalidade do Pitch It.
- [ ] Eu, como um usuário, desejo alterar minhas informações pessoais, para que possa manter meu perfil atualizado.
- [ ] Eu, como um usuário, desejo alterar minha senha de acesso, para que possa garantir a segurança da minha conta.
